- name: Create a jenkins folder using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.name}}"
    token: "119f3d009eefbca2859f1696169f1cd366"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop: "{{folders}}"

- name: Create a jenkins pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: "119f3d009eefbca2859f1696169f1cd366"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop: "{{pipelineJob}}"

- name: Create a jenkins pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'multibranch.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: "119f3d009eefbca2859f1696169f1cd366"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop: "{{multibranchJob}}"