- name: Create a jenkins pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "test"
    token: "119f3d009eefbca2859f1696169f1cd366"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop:
    - { repoName: "cart" , componentName: "cart" }