- name: template
  template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml
  loop:
    - {repoName: "cart" , componentName: "cart"}


- name: Create a jenkins pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "test"
    token: "11f8e41c91ebea5b0d7469c772ec90d081"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"