folders:
  - { name: "CI-Pipeline" , description: "CI Pipeline for roboshop components" }

multibranchJob:
  - { jobName: "cart" , folderName: "CI-Pipeline/" , repoName: "cart" , componentName: "cart" }
  - { jobName: "user" , folderName: "CI-Pipeline/" , repoName: "user" , componentName: "user" }
  - { jobName: "catalogue" , folderName: "CI-Pipeline/" , repoName: "catalogue" , componentName: "catalogue" }
  - { jobName: "shipping" , folderName: "CI-Pipeline/" , repoName: "shipping" , componentName: "shipping" }
  - { jobName: "payment" , folderName: "CI-Pipeline/" , repoName: "payment" , componentName: "payment" }
  - { jobName: "frontend" , folderName: "CI-Pipeline/" , repoName: "frontend" , componentName: "frontend" }

pipelineJob:
  - { jobName: "Deploy-to-any-dev" , folderName: "" , repoName: "roboshop-jenkins" , fileName: "Jenkinsfile-any-env-deploy"}
  - { jobName: "terraform-mutable" , folderName: "" , repoName: "roboshop-terraform-mutable" , fileName: "Jenkinsfile"}



